// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtYgTCi0QnbBLXGU9lVD82BCfMfpy0pN8',
    appId: '1:451304047939:android:2833a2b8ca9673ad785bf6',
    messagingSenderId: '451304047939',
    projectId: 'numu-app-2ca93',
    databaseURL: 'https://numu-app-2ca93-default-rtdb.firebaseio.com',
    storageBucket: 'numu-app-2ca93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJ9ypXwTWQzdQIrjRGbOLNYPa1wz9HzE',
    appId: '1:451304047939:ios:f0c6b04a6cd61546785bf6',
    messagingSenderId: '451304047939',
    projectId: 'numu-app-2ca93',
    databaseURL: 'https://numu-app-2ca93-default-rtdb.firebaseio.com',
    storageBucket: 'numu-app-2ca93.firebasestorage.app',
    iosBundleId: 'com.numuapp.numuapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFuX2YP8KsHoeSy4GRAHQ7rSSPKz2S8ss',
    appId: '1:451304047939:web:702e28e507f8fb3e785bf6',
    messagingSenderId: '451304047939',
    projectId: 'numu-app-2ca93',
    authDomain: 'numu-app-2ca93.firebaseapp.com',
    databaseURL: 'https://numu-app-2ca93-default-rtdb.firebaseio.com',
    storageBucket: 'numu-app-2ca93.firebasestorage.app',
    measurementId: 'G-2ERB9P0B03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFuX2YP8KsHoeSy4GRAHQ7rSSPKz2S8ss',
    appId: '1:451304047939:web:3d10447382799d5b785bf6',
    messagingSenderId: '451304047939',
    projectId: 'numu-app-2ca93',
    authDomain: 'numu-app-2ca93.firebaseapp.com',
    databaseURL: 'https://numu-app-2ca93-default-rtdb.firebaseio.com',
    storageBucket: 'numu-app-2ca93.firebasestorage.app',
    measurementId: 'G-43VK93KMLV',
  );

}